### PR TITLE
Speedup: skip GPG key import when already imported

### PR DESCRIPTION
**Pull request by rud**
Since the key-server sometimes errors out, not re-doing an import all the time seems like a good idea.

What do you think of this solution?

### CODE REVIEW

**Comment by allomov** [comment]
I also have this issue. Here is an error output:
```
TASK: [rvm_io.rvm1-ruby | Import GPG keys] ************************************
failed: [x.x.x.x] => {"changed": false, "cmd": ["gpg", "--keyserver", "hkp://keys.gnupg.net", "--recv-keys", "D39DC0E3"], "delta": "0:01:01.481040", "end": "2015-05-20 08:33:16.694057", "rc": 2, "start": "2015-05-20 08:32:15.213017", "warnings": []}
stderr: gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
stdout: gpgkeys: key D39DC0E3 can't be retrieved

FATAL: all hosts have already failed -- aborting
```

**Comment by rud** [comment]
Alright, so I'm not the only one seeing the issue, good place to start. The build failed, but I'm not at all sure why. Do the tests fail regularly without a real issue or is this something I need to fix before this can be integrated?

**Comment by rud** [comment]
I've rebased on the latest `master` and re-pushed, we'll see if the build error is transient.

**Comment by rud** [comment]
Any feedback on this? I still think it a valuable change

**Comment by nickjj** [comment]
Hi,

The tests being ran aren't random. It's failing the Idempotence test which ensures that if you run the playbook twice it will produce no changes on the second run.

All of the tests can be found in the travis file:
https://github.com/rvm/rvm1-ansible/blob/master/.travis.yml#L15-L47

And the test setup for the role can be found here:
https://github.com/rvm/rvm1-ansible/tree/master/tests

I'd like to see what happens with @mpapis' key when it expires in a few days according to this issue, it's set to expire on Oct 28th 2015. https://github.com/rvm/rvm1-ansible/issues/31#issuecomment-120408301

**Comment by rud** [comment]
With this change, first and second run will have different output. Second and third will be identical. Fwiw.

**Pull request closed without merging**
