### PR TITLE
Check rvm1_delete_ruby is defined

### LINKED ISSUE #156: Error while evaluating conditional (rvm1_delete_ruby): 'ruby' is undefined
When I try to delete an older version of ruby using `rvm1_delete_ruby`, I get the following error:

```
TASK [rvm_io.ruby : Detect if ruby version can be deleted] *************************************************************
fatal: [hostname]: FAILED! => {"failed": true, "msg": "The conditional check 'rvm1_delete_ruby' failed. The error was: error while evaluating conditional (rvm1_delete_ruby): 'ruby' is undefined\n\nThe error appears to have been in '/Users/jeff.geerling/playbook/roles/rvm_io.ruby/tasks/rubies.yml': line 65, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Detect if ruby version can be deleted\n  ^ here\n"}
```

Tried this on two servers where I had `rvm1_rubies: ['ruby-2.3.3']` originally, then set `rvm1_rubies: ['ruby-2.3.4']`, and added the variable `rvm1_delete_ruby: ruby-2.3.1` and ran the playbook again.

### PR DESCRIPTION
**Pull request by gpeng**
Fixes `'ruby' is undefined` error when using `rvm1_delete_ruby`

Fixes #156

### CODE REVIEW

**Comment by pkuczynski** [comment]
Looks good, thx! Could u please also update CHANGELOG?

**Comment by pkuczynski** [comment]
Seems that your PR fails with following error message:

```
The conditional check 'rvm1_delete_ruby if defined' failed. The error was: template error while templating string: expected token 'end of statement block', got 'if'. String: {% if rvm1_delete_ruby if defined %} True {% else %} False {% endif %}

The error appears to have been in '/home/travis/build/rvm/rvm1-ansible/tasks/rubies.yml': line 65, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Detect if ruby version can be deleted
  ^ here
```

**Comment by gpeng** [comment]
@pkuczynski I've fixed the issue and added and 'unreleased' CHANGELOG entry. CI is still failing though with GPG issues. We've been seeing this on Ubuntu and fixed by importing the keys before running this role. Not sure what's going on as I tried importing the keys inside the container (on centos6) with exactly the same command as this role is using and it worked fine but fails when Ansible runs it.

**Comment by thbar** [comment]
This would be helpful today. What can we do to help shipping this?

**Comment by mmolinac** [comment]
I got the same error today about `rvm1_delete_ruby`.
I can see that the issue has been solved in this PR, but also that the tests are complaining about:
```
"ERROR:  Error installing bundler:\n\tbundler requires Ruby version >= 2.3.0."
```
Could somebody fix the required bundler version or Ruby test version instead, please ?

**Comment by pkuczynski** [comment]
@Kulgar which check is better? `| bool` or `is defined`?

**Comment by thbar** [comment]
@rvm/ansible I believe this is a duplicate of https://github.com/rvm/rvm1-ansible/pull/212 (which I'm currently testing). Both will need a bit more work. I'll close this one, but please re-open if my evaluation is incorrect.

Thanks @gpeng for the initial work though!

**Pull request closed without merging**
