### PR TITLE
Fix Ansible Galaxy URL again

### PR DESCRIPTION
**Pull request by veger**
As mentioned by @thbar in #117, the URL changed again

### CODE REVIEW

**Comment by Oliboy50** [comment]
@veger i was trying to install ruby, and it failed, what is the good name of the package now ?

https://galaxy.ansible.com/api/v1/roles/?owner__username=rvm_io&name=ruby

rvm_io.ruby seems to work now :/

**Comment by Oliboy50** [comment]
Is this going to be (and stay) the new package name that we should use in our Galaxy requirements?
Or is this just temporary stuff?

**Comment by veger** [comment]
I just (yesterday) made a PR to update the URL, as I was following it to a non-existing page.
Now it is changed (again), so I created another PR to fix the link to galaxy.

I do not know the plans of the maintainers/developers, so I cannot answer your questions.

**Comment by pkuczynski** [comment]
Thanks!

**Comment by Oliboy50** [comment]
@pkuczynski any answer to my question [here](https://github.com/rvm/rvm1-ansible/pull/120#issuecomment-261642124)?

**Comment by pkuczynski** [comment]
@Oliboy50 which question?

**Pull request merged**
