### PR TITLE
Update Ruby versions.

### PR DESCRIPTION
**Pull request by boone**

### CODE REVIEW

**Comment by Yanchek99** [comment]
+1

**Comment by nickjj** [comment]
Thanks for the contribution but the problem with using `2.2.3` is rvm only has precompiled binaries for `2.2.1` for most major platforms.

I feel like a big benefit of using rvm is that you can get ruby installed without having to compile it on your server. If you want to adjust your PR to use `2.2.1`, then I will accept it.

**Comment by boone** [comment]
@nickjj thanks for the response. I'm reluctant to specify Ruby 2.2.1 for a couple reasons:

* `defaults/main.yml` already specifies 2.2.2, going to 2.2.1 would be rolling the version back
* I feel that Rubies with security updates should be favored over the convenience of binaries

I opened https://github.com/rvm/rvm-binary/pull/25, hoping to get some 2.2.3 binaries generated for Linux, but so far nobody has replied. It would be great to have RVM binaries for the latest Ruby which would make everyone happy. :smile:

**Comment by boone** [comment]
The Ruby version was updated in #98, closing.

**Pull request closed without merging**
