### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by claasz**
Ubuntu 20.04 hosts need acl package installed

### CODE REVIEW

**Comment by pkuczynski** [comment]
@lpaulmp what you think?

**Comment by pkuczynski** [comment]
@rvm/ansible guys can you have a look, please?

**Comment by derekgottlieb** [comment]
I'm able to run this galaxy module while specifying `rvm1_user` against an Ubuntu 20.04 host without the `acl` package installed without encountering this error, so I was curious what's different between our environments. Ignoring potential version differences, there are a lot of ways to use/configure ansible, call this module, etc. From reading the following section of the ansible docs, it sounds like someone might run into this depending on how they have a variety of ansible options set and can solve it in a few different ways:

https://docs.ansible.com/ansible/latest/user_guide/become.html#id6

Since it sounds like this is a more general issue people might run into and not specific to Ubuntu 20.04, perhaps we could include something more general in the help text here? I'm tempted to suggest we link to the ansible docs so people are aware of the other suggested options, but I don't know how "stable" the ansible docs are.

**Comment by pkuczynski** [comment]
Thanks @derekgottlieb! @claasz would you find some time to update this PR?

**Comment by thbar** [comment]
I cannot yet test on Ubuntu 20 (I'm migrating a client to Ubuntu 18, and Ubuntu 20 will come later in the coming months). I will make sure to report back any trouble I see in that area.

**Comment by thbar** [comment]
After re-reading the discussion, I agree with @derekgottlieb: we'll have to rewrite the content to make it clear it is only a potential error, and most likely not specific to Ubuntu 20.

**Review by pkuczynski — APPROVED** [review]

**Pull request merged**
